<template>
  <el-card><template #header><div class="header"><strong>数据范围</strong><el-button v-if="auth.hasPermission('iam:data-scope:write')" type="primary" @click="open()">新增策略</el-button></div></template><el-table :data="items"><el-table-column label="角色"><template #default="s">{{ roleName(s.row.roleId) }}</template></el-table-column><el-table-column label="应用"><template #default="s">{{ appName(s.row.applicationId) }}</template></el-table-column><el-table-column prop="scopeKey" label="范围键"/><el-table-column prop="scopeType" label="范围"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="s"><el-button v-if="auth.hasPermission('iam:data-scope:write')" link type="primary" @click="open(s.row)">编辑</el-button></template></el-table-column></el-table></el-card>
  <el-dialog v-model="dialog" title="数据范围"><el-form label-width="100px"><el-form-item label="角色"><el-select v-model="form.roleId"><el-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.id"/></el-select></el-form-item><el-form-item label="应用"><el-select v-model="form.applicationId"><el-option v-for="a in apps.applications" :key="a.id" :label="a.name" :value="a.id"/></el-select></el-form-item><el-form-item label="范围键"><el-input v-model="form.scopeKey" placeholder="如 sales-data"/></el-form-item><el-form-item label="范围类型"><el-select v-model="form.scopeType"><el-option v-for="t in types" :key="t" :label="t" :value="t"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { ElMessage } from 'element-plus';import { apiClient } from '@/api';import { useApplicationStore,useAuthStore } from '@/stores';import type { DataScopeRecord,RoleRecord } from '@/types/management'
const auth=useAuthStore();const apps=useApplicationStore();const items=ref<DataScopeRecord[]>([]);const roles=ref<RoleRecord[]>([]);const dialog=ref(false);const editingId=ref('');const types=['SELF','MY_STORES','MY_CITY','MY_REGION','ALL'];const form=reactive({roleId:'',applicationId:'',scopeKey:'',scopeType:'SELF',status:'ACTIVE',version:0})
async function load(){[items.value,roles.value]=await Promise.all([apiClient.get('/management/tenant/data-scopes') as Promise<DataScopeRecord[]>,apiClient.get('/management/tenant/roles') as Promise<RoleRecord[]>]);if(!apps.loaded)await apps.fetchApplications()}
function open(row?:DataScopeRecord){editingId.value=row?.id||'';Object.assign(form,row||{roleId:'',applicationId:'',scopeKey:'',scopeType:'SELF',status:'ACTIVE',version:0});dialog.value=true}
function roleName(id:string){return roles.value.find(r=>r.id===id)?.name||id}function appName(id:string){return apps.applications.find(a=>a.id===id)?.name||id}
async function save(){if(editingId.value)await apiClient.put(`/management/tenant/data-scopes/${editingId.value}`,form);else await apiClient.post('/management/tenant/data-scopes',form);ElMessage.success('保存成功');dialog.value=false;await load()}
onMounted(()=>{void load()})
</script><style scoped>.header{display:flex;justify-content:space-between;align-items:center}</style>
