import type { NavigationNode } from '@/types/management'
import { SUPPLY_DOMAIN_ROUTE_MAP } from '@/views/supply-chain/domain/catalog'

/** 数据库routeKey到已编译路由的唯一允许映射；未知或路径不一致时失败关闭。 */
const ROUTES: Record<string, string | null> = {
  'platform.dashboard': '/platform-admin', 'platform.tenant.menu': null,
  'platform.tenant.list': '/platform-admin/tenants', 'platform.package.menu': null,
  'platform.package.list': '/platform-admin/packages', 'platform.application.menu': null,
  'platform.application.list': '/platform-admin/applications', 'platform.resource.menu': null,
  'platform.resource.list': '/platform-admin/resources', 'platform.audit.menu': null,
  'platform.audit.list': '/platform-admin/audit', 'platform.dictionary.menu': null,
  'platform.dictionary.list': '/platform-admin/dictionaries',
  'system.dashboard': '/system-admin', 'system.organization.menu': null,
  'system.organization.list': '/system-admin/organizations', 'system.user.menu': null,
  'system.user.list': '/system-admin/users', 'system.role.menu': null,
  'system.role.list': '/system-admin/roles', 'system.data-scope.menu': null,
  'system.data-scope.list': '/system-admin/data-scopes', 'system.setting.menu': null,
  'system.setting.list': '/system-admin/settings', 'system.menu-config.list': '/system-admin/menus',
  'system.dictionary.menu': null,
  'system.dictionary.list': '/system-admin/dictionaries', 'system.audit.menu': null,
  'system.audit.list': '/system-admin/audit',
  'supply.dashboard': '/supply-chain', 'supply.city.menu': null, 'supply.city.index': '/supply-chain/city',
  'supply.crm.menu': null, 'supply.crm.index': '/supply-chain/crm', 'supply.order.menu': null, 'supply.order.group': null,
  'supply.order.index': '/supply-chain/order',
  'supply.order.center.menu': null,
  'supply.order.fulfillment.menu': null,
  'supply.order.after-sales.menu': null,
  'supply.order.settlement.menu': null,
  'supply.order.all': '/supply-chain/order/all',
  'supply.order.pending': '/supply-chain/order/pending',
  'supply.order.exceptions': '/supply-chain/order/exceptions',
  'supply.order.access.backstage': '/supply-chain/order/access/backstage',
  'supply.order.access.exceptions': '/supply-chain/order/access/exceptions',
  'supply.order.fulfillment.ownership': '/supply-chain/order/fulfillment/ownership',
  'supply.order.fulfillment.inventory': '/supply-chain/order/fulfillment/inventory',
  'supply.order.fulfillment.exceptions': '/supply-chain/order/fulfillment/exceptions',
  'supply.order.after-sales.exchanges': '/supply-chain/order/after-sales/exchanges',
  'supply.order.after-sales.approvals': '/supply-chain/order/after-sales/approvals',
  'supply.order.settlement.receivable': '/supply-chain/order/settlement/receivable',
  'supply.order.settlement.collections': '/supply-chain/order/settlement/collections',
  'supply.order.settlement.reconciliation': '/supply-chain/order/settlement/reconciliation',
  'supply.order.order-list': '/supply-chain/order/orders',
  'supply.order.stock-up': '/supply-chain/order/stock-up',
  'supply.order.shipments': '/supply-chain/order/shipments',
  'supply.order.returns': '/supply-chain/order/returns',
  'supply.order.delivery-partners': '/supply-chain/order/delivery-partners',
  'supply.order.stats': null,
  'supply.order.stats-goods': '/supply-chain/order/stats/goods',
  'supply.order.stats-pending-stock': '/supply-chain/order/stats/pending-stock',
  'supply.order.stats-shipped': '/supply-chain/order/stats/shipped',
  'supply.order.stats-pending-delivery': '/supply-chain/order/stats/pending-delivery',
  'supply.order.stats-returns': '/supply-chain/order/stats/returns',
  'supply.order.goods': '/supply-chain/order/goods',
  'supply.order.marketing': '/supply-chain/order/marketing',
  'supply.order.inventory': '/supply-chain/order/inventory',
  'supply.order.customer': '/supply-chain/order/customer',
  'supply.order.finance': '/supply-chain/order/finance',
  'supply.order.report': '/supply-chain/order/report',
  'supply.order.data': '/supply-chain/order/data',
  'supply.order.system': '/supply-chain/order/system',
  'supply.sales.menu': null, 'supply.sales.dashboard': '/supply-chain/sales',
  'supply.sales.attendance.menu': null,
  'supply.sales.attendance.today': '/supply-chain/sales/attendance/today',
  'supply.sales.attendance.punches': '/supply-chain/sales/attendance/punches',
  'supply.sales.attendance.days': '/supply-chain/sales/attendance/days',
  'supply.sales.attendance.interruptions': '/supply-chain/sales/attendance/interruptions',
  'supply.sales.attendance.adjustments': '/supply-chain/sales/attendance/adjustments',
  'supply.sales.visits.menu': null,
  'supply.sales.visits.plans': '/supply-chain/sales/visits/plans',
  'supply.sales.visits.records': '/supply-chain/sales/visits/records',
  'supply.sales.visits.reviews': '/supply-chain/sales/visits/reviews',
  'supply.sales.visits.appeals': '/supply-chain/sales/visits/appeals',
  'supply.sales.stores.menu': null,
  'supply.sales.stores.assigned': '/supply-chain/sales/stores/assigned',
  'supply.sales.stores.uncovered': '/supply-chain/sales/stores/uncovered',
  'supply.sales.stores.visited': '/supply-chain/sales/stores/visited',
  'supply.sales.stores.effective': '/supply-chain/sales/stores/effective',
  'supply.sales.stores.candidates': '/supply-chain/sales/stores/candidates',
  'supply.sales.organization.menu': null,
  'supply.sales.organization.profiles': '/supply-chain/sales/organization/profiles',
  'supply.sales.organization.teams': '/supply-chain/sales/organization/teams',
  'supply.sales.organization.scopes': '/supply-chain/sales/organization/scopes',
  'supply.sales.tasks.menu': null,
  'supply.sales.tasks.visits': '/supply-chain/sales/tasks/visits',
  'supply.sales.tasks.targets': '/supply-chain/sales/tasks/targets',
  'supply.sales.tasks.exemptions': '/supply-chain/sales/tasks/exemptions',
  'supply.sales.exceptions.menu': null,
  'supply.sales.exceptions.punch': '/supply-chain/sales/exceptions/punch',
  'supply.sales.exceptions.location': '/supply-chain/sales/exceptions/location',
  'supply.sales.exceptions.evidence': '/supply-chain/sales/exceptions/evidence',
  'supply.sales.exceptions.recording': '/supply-chain/sales/exceptions/recording',
  'supply.sales.exceptions.reviews': '/supply-chain/sales/exceptions/reviews',
  'supply.sales.policies.menu': null,
  'supply.sales.policies.field': '/supply-chain/sales/policies/field',
  'supply.sales.policies.visit': '/supply-chain/sales/policies/visit',
  'supply.sales.policies.recording-ai': '/supply-chain/sales/policies/recording-ai',
  'supply.sales.policies.scopes': '/supply-chain/sales/policies/scopes',
  'supply.sales.policies.releases': '/supply-chain/sales/policies/releases',
  'supply.erp.menu': null, 'supply.erp.index': '/supply-chain/erp', 'supply.hr.menu': null,
  'supply.hr.index': '/supply-chain/hr', 'supply.channel.menu': null, 'supply.channel.index': '/supply-chain/channel',
  'supply.bi.menu': null, 'supply.bi.index': '/supply-chain/bi', 'supply.setting.menu': null,
  'supply.setting.index': '/supply-chain/settings', 'supply.dhb.menu': null,
  'supply.integration.overview': '/supply-chain/integration',
  'supply.integration.raw-data': '/supply-chain/integration/raw-data',
  'supply.integration.sync-tasks': '/supply-chain/integration/sync-tasks',
  'supply.integration.retries': '/supply-chain/integration/retries-dead-letters',
  'supply.integration.connections': '/supply-chain/integration/connections',
  'supply.integration.field-mappings': '/supply-chain/integration/field-mappings',
  'supply.integration.reconciliation': '/supply-chain/integration/reconciliation',
  'supply.integration.sovereignty': '/supply-chain/integration/sovereignty',
  ...SUPPLY_DOMAIN_ROUTE_MAP,
}

export function validateNavigation(nodes: NavigationNode[]): NavigationNode[] {
  return nodes.map((node) => {
    const tenantGroup = node.type === 'MENU'
      && node.routeKey.startsWith('tenant.menu.group.')
      && node.routePath === null
    if (!tenantGroup && (!(node.routeKey in ROUTES) || ROUTES[node.routeKey] !== node.routePath)) {
      throw new Error(`IAM返回未注册或路径不一致的routeKey: ${node.routeKey}`)
    }
    return { ...node, children: validateNavigation(node.children) }
  })
}
