<template>
  <el-card><template #header><div class="header"><div><strong>角色与资源授权</strong><small>只能授予当前有效套餐内的菜单、页面、按钮和 API 资源</small></div><el-button v-if="canManage" type="primary" @click="open()">新增角色</el-button></div></template>
    <el-table :data="roles"><el-table-column prop="code" label="角色编码"/><el-table-column prop="name" label="角色名称"/><el-table-column label="类型"><template #default="scope"><el-tag :type="scope.row.type==='SYSTEM'?'warning':'info'">{{scope.row.type==='SYSTEM'?'系统保护':'自定义'}}</el-tag></template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column label="已授权资源"><template #default="s">{{ s.row.resourceIds.length }}</template></el-table-column><el-table-column label="操作"><template #default="s"><el-button v-if="canManage&&s.row.type==='CUSTOM'" link type="primary" @click="open(s.row)">配置</el-button><span v-else-if="s.row.type==='SYSTEM'" class="protected">由 IAM 维护</span></template></el-table-column></el-table>
  </el-card><el-dialog v-model="dialog" title="自定义角色及资源授权" width="720px"><el-form label-width="100px"><el-form-item label="角色编码"><el-input v-model="form.code" :disabled="!!editingId"/></el-form-item><el-form-item label="角色名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item><el-form-item label="资源权限"><el-tree ref="treeRef" :data="resourceTree" node-key="id" show-checkbox :props="{label:'displayName',children:'children'}"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, ref } from 'vue';import { ElMessage, type ElTree } from 'element-plus';import { apiClient } from '@/api';import { useAuthStore } from '@/stores';import type { ResourceRecord,RoleRecord } from '@/types/management'
interface ResourceTreeNode extends ResourceRecord{children:ResourceTreeNode[]}
const auth=useAuthStore();const roles=ref<RoleRecord[]>([]);const resources=ref<ResourceRecord[]>([]);const dialog=ref(false);const editingId=ref('');const treeRef=ref<InstanceType<typeof ElTree>>();const form=reactive({code:'',name:'',type:'CUSTOM',status:'ACTIVE',version:0});const canManage=computed(()=>auth.hasPermission('iam:role:write')&&auth.hasPermission('iam:role:grant'))
const resourceTree=computed<ResourceTreeNode[]>(()=>{const nodes=new Map<string,ResourceTreeNode>();resources.value.forEach(r=>nodes.set(r.id,{...r,children:[]}));const roots:ResourceTreeNode[]=[];nodes.forEach(n=>{const p=n.parentId?nodes.get(n.parentId):undefined;if(p)p.children.push(n);else roots.push(n)});return roots})
async function load(){[roles.value,resources.value]=await Promise.all([apiClient.get('/management/tenant/roles') as Promise<RoleRecord[]>,apiClient.get('/management/tenant/grantable-resources') as Promise<ResourceRecord[]>])}
async function open(row?:RoleRecord){editingId.value=row?.id||'';Object.assign(form,row||{code:'',name:'',type:'CUSTOM',status:'ACTIVE',version:0});dialog.value=true;await nextTick();treeRef.value?.setCheckedKeys(row?.resourceIds||[])}
async function save(){const resourceIds=(treeRef.value?.getCheckedKeys(false)||[]).map(String);const payload={...form,resourceIds};if(editingId.value)await apiClient.put(`/management/tenant/roles/${editingId.value}`,payload);else await apiClient.post('/management/tenant/roles',payload);ElMessage.success('保存成功');dialog.value=false;await load()}
onMounted(()=>{void load()})
</script><style scoped>.header{display:flex;justify-content:space-between;align-items:center}.header>div{display:grid;gap:4px}.header small,.protected{color:#8a97a8;font-size:12px;font-weight:400}:deep(.el-tree){max-height:360px;overflow:auto;width:100%}</style>
